### ISSUE TITLE
Publish fixed version to NuGet

### ISSUE THREAD

**Issue by enikao** [gragra33/Utf8JsonAsyncStreamReader#3]
We'd like to use the fix from #2 via [NuGet](https://www.nuget.org/packages/Utf8JsonAsyncStreamReader).

Could you publish a new version of the package?
Thanks.

**Comment by gragra33** [comment]
I'll sort it out this weekend

**Comment by gragra33** [comment]
@enikao published. Also supports .Net 8.0

**Comment by enikao** [comment]
thanks a lot @gragra33 (-:
